name: Create PR deploy to staging

on:
  pull_request:
    types:
      - closed
    branches:
      - deploy

jobs:
  create-pr-deploy-to-staging:
    if: >
      github.event.pull_request.merged == true &&
      github.event.pull_request.head.ref != 'staging'
    uses: ./.github/workflows/create-pull-request.yml
    with:
      head_branch: deploy
      base_branch: staging
      pr_title: "deploy -> staging (#${{ github.event.pull_request.number }})"
      pr_body: |
        このPRは、以下のPRの変更内容を `staging` ブランチに反映するためのものです。

        - 元PR: #${{ github.event.pull_request.number }}

    secrets:
      app_id: ${{ secrets.TANUKI_2_APP_ID }}
      app_private_key: ${{ secrets.TANUKI_2_PRIVATE_KEY }}
