name: Merge PR staging to develop

on:
  pull_request:
    types: 
      - opened
    branches:
      - develop

jobs:
  merge-pr-staging-to-develop:
    if: startsWith(github.event.pull_request.head.ref, 'auto/')
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Status Checks to Pass
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const { data: checks } = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: pr.head.sha,
            });

            const ignored = ['merge-pr-staging-to-develop'];
            const allPassing = checks.check_runs
              .filter(c => !ignored.includes(c.name))
              .every(c => c.status === 'completed' && c.conclusion === 'success');

            if (!allPassing) {
              core.setFailed("Not all required checks have passed.");
            }

      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Merge PR
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --delete-branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
