name: Merge or Pull Request A to B

on:
  push:
    branches:
      - deploy

jobs:
  merge-or-pull-request-a-to-b:
    uses: ./.github/workflows/merge-or-pull-request.yml
    with:
      base_branch: staging
      head_branch: deploy
      next_workflow: merge-or-pull-request-b-to-c.yml
