name: Create PR deploy to staging

on:
  pull_request:
    types:
      - closed
    branches:
      - deploy

jobs:
  create-pull-request:
    if: >
      github.event.pull_request.merged == true &&
      github.event.pull_request.head.ref != 'staging'
    uses: ./.github/workflows/create-pull-request.yml
    with:
      head_branch: deploy
      base_branch: staging
      pr_title: "deploy -> staging (#${{ github.event.pull_request.number }})"
      pr_body: |
        このPRは、以下のPRの変更内容を \`staging\` ブランチに反映するためのものです。

        - pr: #${{ github.event.pull_request.number }}
        - author: ${{ github.event.pull_request.user.login }}
      assignees: ${{ github.event.pull_request.user.login }}
      reviewers: ${{ github.event.pull_request.user.login }}
      labels: "auto pr action required"
    secrets:
      app_id: ${{ secrets.TANUKI_2_APP_ID }}
      app_private_key: ${{ secrets.TANUKI_2_PRIVATE_KEY }}