name: Always Fail on PR to develop

on:
  pull_request:
    types:
      - opened
    branches:
      - develop

jobs:
  always-fail:
    runs-on: ubuntu-latest
    steps:
      - name: Intentionally fail
        run: |
          echo "🔥 PR opened to develop → fail by design"
          exit 1
