name: on-all-job-finished

on:
  workflow_run:
    workflows:
      - "*"
    types:
      - completed

jobs:
  check_if_all_job_finished:
    if: startsWith(github.event.workflow_run.head_branch, 'auto/staging')
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/github-script@v7
        id: all-workflow-summary
        with:
          script: |
            // ref: https://github.com/actions/github-script#run-a-separate-file
            return await require('./.github/scripts/check-workflow-run-status.cjs')({ github, context })
          result-encoding: string
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: log_success
        if: steps.all-workflow-summary.outputs.result == 'SUCCESS_ALL'
        run: |
          echo "すべてのチェックが成功しました:tada:"