name: Auto Merge on CI Success

on:
  workflow_run:
    workflows:
      - "*"
    types:
      - completed
    branches:
      - 'auto/staging-*'
env:
  BASE_BRANCH: develop
  DISPATCH_NOTIFY_REPOSITORIES: test-notify
  DISPATCH_NOTIFY_EVENT_TYPE: test-notify
  REQUIRED_ACTION_TYPE_FAIL_CI: auto-create-pr-fail-ci

jobs:
  auto-merge-on-ci-success:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      ci_status: ${{ steps.check-ci-status.outputs.result }}
      pr_number: ${{ steps.find-pull-request.outputs.number }}
      pr_title: ${{ steps.find-pull-request.outputs.title }}
      pr_html_url: ${{ steps.find-pull-request.outputs.html_url }}
      pr_original_author: ${{ steps.find-pull-request.outputs.original_author }}
    steps:
      - id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.TANUKI_2_APP_ID }}
          private-key: ${{ secrets.TANUKI_2_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/github-script@v7
        id: check-ci-status
        with:
          script: |
            return await require('./.github/scripts/check-ci-status.cjs')({ github, context })
          result-encoding: string
          github-token: ${{ steps.app-token.outputs.token }}
  
      - name: Find Pull Request
        id: find-pull-request
        if: steps.check-ci-status.outputs.result != 'IN_PROGRESS'
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            const headSha = context.payload.workflow_run.head_sha;
            const headBranch = context.payload.workflow_run.head_branch;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const res = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner,
              repo,
              commit_sha: headSha
            });

            const pr = res.data.find(pr =>
              pr.state === 'open' &&
              pr.head.ref === headBranch &&
              pr.base.ref === process.env.BASE_BRANCH
            );

            core.setOutput('number', pr?.number ?? '');
            core.setOutput('html_url', pr?.html_url ?? '');
            core.setOutput('title', pr?.title ?? '');
            core.setOutput('original_author', pr?.body?.match(/original author: (.+)/)?.[1] ?? '');

      - name: Merge Pull Request
        if: steps.check-ci-status.outputs.result == 'SUCCESS_ALL'
        run: |
          gh pr merge ${{ steps.find-pull-request.outputs.number }} --merge --auto
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Request Pull Request Review
        if: >
          steps.check-ci-status.outputs.result != 'IN_PROGRESS' &&
          steps.check-ci-status.outputs.result != 'SUCCESS_ALL'
        run: |
          REVIEWERS_JSON="{\"reviewers\":[\"${{ steps.find-pull-request.outputs.original_author }}\"]}"
          curl -s -X POST \
            -H "Authorization: token ${{ steps.app-token.outputs.token }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ steps.find-pull-request.outputs.number }}/requested_reviewers \
            -d "$REVIEWERS_JSON"

  is-ci-fail-dispatch-notify:
    needs: auto-merge-on-ci-success
    if: > 
      needs.auto-merge-on-ci-success:.outputs.ci_status != 'IN_PROGRESS' && 
      needs.auto-merge-on-ci-success:.outputs.ci_status != 'SUCCESS_ALL' &&
      needs.auto-merge-on-ci-success:.outputs.pr_number != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: dispatch-notify-token
        with:
          app-id: ${{ secrets.TANUKI_2_APP_ID }}
          private-key: ${{ secrets.TANUKI_2_PRIVATE_KEY }}
          repositories: ${{ env.DISPATCH_NOTIFY_REPOSITORIES }}

      - name: Dispatch Notify Workflow
        run: |
          JSON_PAYLOAD=$(jq -n \
            --arg event_type "${{ env.DISPATCH_NOTIFY_EVENT_TYPE }}" \
            --arg required_action_type "${{ env.REQUIRED_ACTION_TYPE_CONFLICT }}" \
            --arg author "${{ needs.auto-merge-on-ci-success:.outputs.pr_original_author }}" \
            --arg pr_number "${{ needs.auto-merge-on-ci-success:.outputs.pr_number }}" \
            --arg pr_title "${{ needs.auto-merge-on-ci-success:.outputs.pr_title }}" \
            --arg pr_html_url "${{ needs.auto-merge-on-ci-success:.outputs.pr_html_url }}" \
            '{
              event_type: $event_type,
              client_payload: {
                required_action_type: $required_action_type,
                author: $author,
                pull_request: {
                  number: ($pr_number | tonumber),
                  title: $pr_title,
                  html_url: $pr_html_url
                }
              }
            }'
          )

          curl -s -X POST \
            -H "Authorization: Bearer ${{ steps.dispatch-notify-token.outputs.token }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository_owner }}/${{ env.DISPATCH_NOTIFY_REPOSITORIES }}/dispatches \
            -d "$JSON_PAYLOAD"
