name: Concurrent Workflow 3

on:
  push:
    branches:
      - 'trigger/**'
  workflow_dispatch:

jobs:
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Workflow 3
        run: |
          echo "Starting Concurrent Workflow 3"
          echo "Current time: $(date)"
          sleep 20
          echo "Workflow 3 completed"
