name: Create PR

on:
  workflow_call:
    inputs:
      head_branch:
        required: true
        type: string
      base_branch:
        required: true
        type: string
      pr_title:
        required: true
        type: string
    secrets:
      app_id:
        required: true
      app_private_key:
        required: true

jobs:
  craete-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.app_id }}
          private-key: ${{ secrets.app_private_key }}
          
      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Set up Git config
        run: |
          git config user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
      
      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.base_branch }}
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0

      - name: Fetch head branch
        run: |
          git fetch origin ${{ inputs.head_branch }}:${{ inputs.head_branch }}

      - name: Create PR
        run: |
          TEMP_HEAD_BRANCH=auto/${{ inputs.head_branch }}-$(date +%s)
          git checkout -b $TEMP_HEAD_BRANCH ${{ inputs.head_branch }}
          git push origin $TEMP_HEAD_BRANCH

          COMMITS=$( \
            curl -s \
              -H "Authorization: token ${{ steps.app-token.outputs.token }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/commits?sha=${{ inputs.head_branch }}&per_page=10")

          LAST_HUMAN_USER=$(echo "$COMMITS" | jq -r '.[] | select(.author.login != null and (.author.login | test("\\[bot\\]$") | not)) | .author.login' | head -n 1)

          curl -s -X POST \
            -H "Authorization: token ${{ steps.app-token.outputs.token }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -d "$(jq -n \
              --arg title "${{ inputs.pr_title }}" \
              --arg head "$TEMP_HEAD_BRANCH" \
              --arg base "${{ inputs.base_branch }}" \
              --arg body ".github/pull_request_template.md" \
              '{title: $title, head: $head, base: $base, body: $body}')"

