name: Create PR

on:
  workflow_call:
    inputs:
      head_branch:
        required: true
        type: string
      base_branch:
        required: true
        type: string
      pr_title:
        required: true
        type: string
      pr_body:
        required: false
        default: ""
        type: string
    secrets:
      app_id:
        required: true
      app_private_key:
        required: true
      my_github_token:
        required: true

jobs:
  craete-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.base_branch }}
          token: ${{ secrets.my_github_token: }}
          fetch-depth: 0

      - name: Set up Git config
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      
      - name: Fetch head branch
        run: |
          git fetch origin ${{ inputs.head_branch }}:${{ inputs.head_branch }}

      - name: Create PR
        run: |
          TEMP_HEAD_BRANCH=auto/${{ inputs.head_branch }}-$(date +%s)
          git checkout -b $TEMP_HEAD_BRANCH ${{ inputs.head_branch }}
          git push origin $TEMP_HEAD_BRANCH

          COMMITS=$( \
            curl -s \
              -H "Authorization: token ${{ secrets.my_github_token: }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/commits?sha=${{ inputs.head_branch }}&per_page=10")

          LAST_HUMAN_USER=$(echo "$COMMITS" | jq -r '.[] | select(.author.login != null and (.author.login | test("\\[bot\\]$") | not)) | .author.login' | head -n 1)

          curl -s -X POST \
            -H "Authorization: token ${{ secrets.my_github_token: }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -d "$(jq -n \
              --arg title "${{ inputs.pr_title }}" \
              --arg head "$TEMP_HEAD_BRANCH" \
              --arg base "${{ inputs.base_branch }}" \
              --arg body "${{ inputs.pr_body }}" \
              '{title: $title, head: $head, base: $base, body: $body}')"

