name: Create PR staging to develop

on:
  pull_request:
    types:
      - closed
    branches:
      - staging

jobs:
  create-pull-request:
    if: >
      github.event.pull_request.merged == true &&
      github.event.pull_request.head.ref != 'develop'
    runs-on: ubuntu-latest
    steps:
      - name: Determine PR info
        id: extract-pr-info
        run: |
          if [[ "${{ github.event.pull_request.user.login }}" == *[bot] ]]; then
            ORIGINAL_AUTHOR=$(echo "${{ github.event.pull_request.body }}" | grep -oE 'original author: [a-zA-Z0-9_-]+' | awk '{print $2}')
          else
            ORIGINAL_AUTHOR=${{ github.event.pull_request.user.login }}
          fi
          echo "original_author=$ORIGINAL_AUTHOR" >> "$GITHUB_OUTPUT"

      - name: Call create-pull-request workflow
        id: call-workflow
        uses: ./.github/workflows/create-pull-request.yml
        with:
          head_branch: staging
          base_branch: develop
          pr_title: "staging -> develop (#${{ steps.extract-pr-info.outputs.pr_number }})"
          pr_body: |
            このPRは、以下のPRの変更内容を \`develop\` ブランチに反映するためのものです。

            - pr: #${{ github.event.pull_request.number }}
            - original author: ${{ steps.extract-pr-info.outputs.original_author }}
        secrets:
          app_id: ${{ secrets.TANUKI_2_APP_ID }}
          app_private_key: ${{ secrets.TANUKI_2_PRIVATE_KEY }}
