name: 🔍 Debug GitHub App Secrets

on:
  workflow_dispatch:

jobs:
  check-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Print part of TANUKI_APP_ID
        run: |
          echo "TANUKI_APP_ID (先頭3桁): ${TANUKI_APP_ID:0:3}..."
        env:
          TANUKI_APP_ID: ${{ secrets.TANUKI_APP_ID }}

      - name: ✅ Check TANUKI_PRIVATE_KEY (.pem)
        run: |
          echo "----- 秘密鍵 (.pem) の検証 -----"
          echo "行数: $(echo \"$TANUKI_PRIVATE_KEY\" | wc -l)"
          echo "先頭行: $(echo \"$TANUKI_PRIVATE_KEY\" | head -n 1)"
          echo "末尾行: $(echo \"$TANUKI_PRIVATE_KEY\" | tail -n 1)"
        env:
          TANUKI_PRIVATE_KEY: ${{ secrets.TANUKI_PRIVATE_KEY }}

      - name: ✅ Check presence of both secrets
        run: |
          if [ -z "$TANUKI_APP_ID" ]; then
            echo "❌ TANUKI_APP_ID is empty"
            exit 1
          fi
          if [ -z "$TANUKI_PRIVATE_KEY" ]; then
            echo "❌ TANUKI_PRIVATE_KEY is empty"
            exit 1
          fi
          echo "✅ 両方のSecretsが確認できました！"
        env:
          TANUKI_APP_ID: ${{ secrets.TANUKI_APP_ID }}
          TANUKI_PRIVATE_KEY: ${{ secrets.TANUKI_PRIVATE_KEY }}
