name: 🔍 Debug GitHub App Secrets

on:
  workflow_dispatch:

jobs:
  check-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Print part of TEST_GITHUB_APP_ID
        run: |
          echo "TEST_GITHUB_APP_ID (先頭3桁): ${TEST_GITHUB_APP_ID:0:3}..."
        env:
          TEST_GITHUB_APP_ID: ${{ secrets.TEST_GITHUB_APP_ID }}

      - name: ✅ Check TEST_GITHUB_APP_PRIVATE_KEY (.pem)
        run: |
          echo "----- 秘密鍵 (.pem) の検証 -----"
          echo "行数: $(echo \"$TEST_GITHUB_APP_PRIVATE_KEY\" | wc -l)"
          echo "先頭行: $(echo \"$TEST_GITHUB_APP_PRIVATE_KEY\" | head -n 1)"
          echo "末尾行: $(echo \"$TEST_GITHUB_APP_PRIVATE_KEY\" | tail -n 1)"
        env:
          TEST_GITHUB_APP_PRIVATE_KEY: ${{ secrets.TEST_GITHUB_APP_PRIVATE_KEY }}

      - name: ✅ Check presence of both secrets
        run: |
          if [ -z "$TEST_GITHUB_APP_ID" ]; then
            echo "❌ TEST_GITHUB_APP_ID is empty"
            exit 1
          fi
          if [ -z "$TEST_GITHUB_APP_PRIVATE_KEY" ]; then
            echo "❌ TEST_GITHUB_APP_PRIVATE_KEY is empty"
            exit 1
          fi
          echo "✅ 両方のSecretsが確認できました！"
        env:
          TEST_GITHUB_APP_ID: ${{ secrets.TEST_GITHUB_APP_ID }}
          TEST_GITHUB_APP_PRIVATE_KEY: ${{ secrets.TEST_GITHUB_APP_PRIVATE_KEY }}
