name: Merge or Pull Request B to C

on:
  workflow_dispatch:
  push:
    branches:
      - staging

jobs:
  merge-or-pull-request-a-to-b:
    uses: ./.github/workflows/merge-or-pull-request.yml
    with:
      head_branch: staging
      base_branch: develop
      tanuki_app_id: ${{ secrets.TANUKI_APP_ID }}
      tanuki_private_key: ${{ secrets.TANUKI_PRIVATE_KEY }}
