name: Workflow Run Trigger Test

on:
  workflow_run:
    workflows:
      - "*"
    types:
      - completed
    branches:
      - "auto/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log Workflow Run Details
        run: |
          echo "Workflow Name: ${{ github.workflow }}"
          echo "Head Branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Head SHA: ${{ github.event.workflow_run.head_sha }}"
          echo "Event Type: ${{ github.event_name }}"
          echo "Workflow Run ID: ${{ github.event.workflow_run.id }}"
          echo "Workflow Run URL: ${{ github.event.workflow_run.html_url }}"